### ISSUE TITLE
Chatt -backend

### ISSUE THREAD

**Issue by Flashkeys** [malinclarsson/mandatory-project-agile1-#41]
Endpoints :  
Post där jag skickar ett obj med 3 nycklar. Jag vill även skicka med ett id på lobbyn i Post
name :
message :
id :

Name ska då vara namnet på personen som skickar meddelandet.

Get där jag ska hämta ett obj med 3 nycklar. Jag vill även skicka med ett id på lobbyn i get
name :
message :
id :

**Comment by sawariz0r** [comment]
Gjorde en uppdaterad issue om detta :)
Se #57
