### ISSUE TITLE
Kolla över våra Labels på Issues

### ISSUE THREAD

**Issue by sawariz0r** [malinclarsson/mandatory-project-agile1-#7]
Jag tror vi kan behöva titta över vad vi ska ha för labels.

Ett par förslag är:
- Bugg
- Ny feature
- Fundering
- Pls help
- Mötesanteckningar
- Todo

**Comment by malinclarsson** [comment]
Låter bra. Ska du eller jag skapa dem @sawariz0r ?

**Comment by sawariz0r** [comment]
Tittar över det just nu, försöker installera actions som sätter lite labels åt oss. Bortse från mina skumma issues :P

**Comment by malinclarsson** [comment]
Super. Hojta till när du är klar, och hur du löste det :)

**Comment by sawariz0r** [comment]
Har lagt till de labelsen jag kom på behövdes och ändrade de till svenska. Stänger denna Issuen och öppnar en ny ang. "auto-labelern"
